# Generated by Django 2.1.7 on 2019-07-09 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('post_created', models.DateTimeField(verbose_name='Post Created')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(verbose_name='Date Created')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='main_userObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to='Board.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_userObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to='Board.User'),
        ),
    ]
